# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do

  desc "Description of what the lane does"
  lane :deploy do
	# Ensure that your git status is not dirty
	ensure_git_status_clean

	# Increment build number
	increment_build_number(
		build_number: latest_testflight_build_number + 1,
		xcodeproj: "PictureMyWorld.xcodeproj"
	)

	# Code Signing
	# cert will make sure you have a valid certificate and its private key installed on the local machine
	# sigh will make sure you have a valid provisioning profile installed locally, that matches the installed certificate
	#get_certificates           # invokes cert
	#get_provisioning_profile   # invokes sigh
	# Build iOS app
	build_app(scheme: "PictureMyWorld", workspace: "PictureMyWorld.xcworkspace", include_bitcode: true)

	# Upload binry to testflight
	upload_to_testflight

	# Commit the version bump
	commit_version_bump(xcodeproj: "PictureMyWorld.xcodeproj")

	# Add a git tag for this build. This will automatically
	# use an appropriate git tag name
	add_git_tag

	# Push the new commit and tag back to your git remote
	push_to_git_remote
  end
end
